<a href="https://colab.research.google.com/github/MeenatchiKV/My-ML-Learnings/blob/master/Multi-Layer-Perceptron_BackProp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

import numpy as np
def sigmoid(x):
    return (1/(1+np.exp(-x)))
def sigmoid_derivative(x):
    return x*(1-x)
#training_input = np.array([[0,0,0,0], [0,0,0,1],[0,0,1,0], [0,0,1,1], [0,1,0,0], [0,1,0,1], [0,1,1,0], [0,1,1,1], [1,0,0,0], [1,0,0,1], [1,0,1,0],[1,0,1,1],[1,1,0,0],[1,1,0,1],[1,1,1,0],[1,1,1,1]])
#training_output = np.array([[0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]]).T

#training_input = np.array([[0,0,0], [0,1,0], [1,0,1], [1,1,1]])
#training_output = np.array([[0,1,1,0]]).T

training_input = np.array([[0,0,0], [0,0,1], [0,1,0], [0,1,1], [1,0,0], [1,0,1], [1,1,0], [1,1,1]])
training_output = np.array([[0,1,0,0,1,1,1,1]]).T

#np.random.seed(1)

inputLayerNeurons, hiddenLayerNeurons, outputLayerNeurons = 3,4,1

hidden_weights = np.random.uniform(size=(inputLayerNeurons,hiddenLayerNeurons))
hidden_bias =np.random.uniform(size=(1,hiddenLayerNeurons))
output_weights = np.random.uniform(size=(hiddenLayerNeurons,outputLayerNeurons))
output_bias = np.random.uniform(size=(1,outputLayerNeurons))


def mse(y,y_cap):
    return (sum(y-y_cap)**2)/8

print('Random Weights:', hidden_weights)
lr = 0.1
for iteration in range(10000):
    input_layer = training_input

    hidden_output = sigmoid(np.dot(input_layer, hidden_weights) + hidden_bias)
    output = sigmoid(np.dot(hidden_output,output_weights)+ output_bias)
    error = training_output - output
    d_predicted_output = error * sigmoid_derivative(output)
    
    error_hidden_layer = d_predicted_output.dot(output_weights.T)
    d_hidden_layer = error_hidden_layer * sigmoid_derivative(hidden_output)

    output_weights += np.dot(hidden_output.T,d_predicted_output) * lr
    output_bias += np.sum(d_predicted_output,axis=0,keepdims=True) * lr
    hidden_weights += input_layer.T.dot(d_hidden_layer) * lr
    hidden_bias += np.sum(d_hidden_layer,axis=0,keepdims=True) * lr
    

print("synaptic weights after training :", hidden_weights)
print("hidden weights after training :", output_weights)
print(" The outputs are :", output)
#print("Error:",error)
print("error: ",mse(training_output,output))

Random Weights: [[0.46828965 0.30890293 0.05698632 0.17152962]
 [0.55320595 0.52716314 0.23150229 0.02285616]
 [0.5643671  0.00459784 0.35524936 0.00539063]]
synaptic weights after training : [[ 1.41891471 -3.41754816 -1.76344143  5.72487749]
 [-0.0628564   1.76922359  0.70524313 -2.93377285]
 [ 1.03354275 -1.72494224 -0.60491087  2.72466091]]
hidden weights after training : [[ 1.39145965]
 [-4.71690735]
 [-2.34652127]
 [ 7.67220276]]
 The outputs are : [[0.0257934 ]
 [0.97134298]
 [0.00134567]
 [0.02531332]
 [0.99876545]
 [0.99943375]
 [0.97981157]
 [0.99890887]]
error:  [6.39050838e-08]


In [ ]:
import numpy as np
def sigmoid(x):
    return (1/(1+np.exp(-x)))
def sigmoid_derivative(x):
    return x*(1-x)

training_input = np.array([[0,0,0], [0,0,1], [0,1,0], [0,1,1], [1,0,0], [1,0,1], [1,1,0], [1,1,1]])
training_output = np.array([[0,1,0,0,1,1,1,1]]).T

nodes_1, nodes_2, nodes_3 = 3,2,1

np.random.seed(1)

hidden_w = 2*np.random.random((nodes_1,nodes_2))-1
hidden_b = np.random.random(size=(1,nodes_2))
output_w = 2*np.random.random((nodes_2,nodes_3))-1
output_b = np.random.random(size=(1,nodes_3))

print('Hidden_Weights:', hidden_w)
print('Hidden_Bias:', hidden_b)
print('Output_Weights:', output_w)
print('Output_Bias:', output_b)

lr = 0.1
epochs = 10000

for i in range(epochs):
    input_l = training_input
    hidden_l = np.dot(input_l, hidden_w) + hidden_b
    hidden_l_out = sigmoid(hidden_l)
    output_l = np.dot(hidden_l_out,output_w) + output_b
    output_l_out = sigmoid(output_l)
    
    error = training_output - output_l_out
    loss = error ** 2
    print('loss : ', loss)
    d_output = error * sigmoid_derivative(output_l_out)
    
    error_hidden = np.dot(d_output,output_w.T)
    d_hidden = error_hidden * sigmoid_derivative(hidden_l_out)
    
    output_w += np.dot(hidden_l_out.T,d_output) * lr
    output_b += np.sum(d_output,axis=0,keepdims=True) * lr
    hidden_w += np.dot(input_l.T,d_hidden) * lr
    hidden_b += np.sum(d_hidden,axis=0,keepdims=True) * lr
    

print("synaptic weights after training :", hidden_w)
print("hidden weights after training :", output_w)
print(" The outputs are :", output_l_out)




Hidden_Weights: [[-0.16595599  0.44064899]
 [-0.99977125 -0.39533485]
 [-0.70648822 -0.81532281]]
Hidden_Bias: [[0.18626021 0.34556073]]
Output_Weights: [[-0.20646505]
 [ 0.07763347]]
Output_Bias: [[0.41919451]]
loss :  [[0.34464185]
 [0.16649385]
 [0.35659591]
 [0.3599072 ]
 [0.16725161]
 [0.1633174 ]
 [0.15929586]
 [0.15767711]]
loss :  [[0.34729937]
 [0.16490286]
 [0.35903713]
 [0.36202728]
 [0.16530151]
 [0.16162949]
 [0.15756054]
 [0.15617915]]
loss :  [[0.34978593]
 [0.16342898]
 [0.36132077]
 [0.36400556]
 [0.16348947]
 [0.16006167]
 [0.15594679]
 [0.15478774]]
loss :  [[0.35211265]
 [0.1620629 ]
 [0.3634572 ]
 [0.36585146]
 [0.16180427]
 [0.15860425]
 [0.15444477]
 [0.15349437]]
loss :  [[0.35428989]
 [0.16079616]
 [0.36545608]
 [0.36757378]
 [0.16023571]
 [0.15724842]
 [0.15304556]
 [0.15229129]]
loss :  [[0.35632734]
 [0.15962105]
 [0.36732643]
 [0.36918068]
 [0.15877451]
 [0.15598618]
 [0.15174102]
 [0.15117145]]
loss :  [[0.35823404]
 [0.15853055]
 [0.36907664]
 [0.37067977

 [0.0603316 ]]
loss :  [[0.20838209]
 [0.19063936]
 [0.12419193]
 [0.20793692]
 [0.05904127]
 [0.03653119]
 [0.08673015]
 [0.05982604]]
loss :  [[0.20745492]
 [0.19056188]
 [0.12276429]
 [0.206899  ]
 [0.0585646 ]
 [0.03609332]
 [0.08646168]
 [0.05932203]]
loss :  [[0.20653252]
 [0.1904785 ]
 [0.12134904]
 [0.20586528]
 [0.05808958]
 [0.03565944]
 [0.08619263]
 [0.05881962]]
loss :  [[0.20561492]
 [0.19038924]
 [0.11994623]
 [0.20483582]
 [0.05761626]
 [0.03522956]
 [0.08592304]
 [0.05831889]]
loss :  [[0.20470215]
 [0.19029411]
 [0.11855593]
 [0.20381068]
 [0.0571447 ]
 [0.03480369]
 [0.08565295]
 [0.0578199 ]]
loss :  [[0.20379424]
 [0.19019312]
 [0.11717818]
 [0.20278992]
 [0.05667495]
 [0.03438187]
 [0.08538239]
 [0.05732273]]
loss :  [[0.20289119]
 [0.19008629]
 [0.11581303]
 [0.2017736 ]
 [0.05620708]
 [0.03396409]
 [0.08511138]
 [0.05682744]]
loss :  [[0.20199303]
 [0.18997364]
 [0.11446053]
 [0.20076177]
 [0.05574113]
 [0.03355037]
 [0.08483997]
 [0.05633409]]
loss :  [[0.20109

 [0.00371609]]
loss :  [[0.06449646]
 [0.07726933]
 [0.0041011 ]
 [0.055525  ]
 [0.00418205]
 [0.00141363]
 [0.03288212]
 [0.00369178]]
loss :  [[0.06429784]
 [0.0770283 ]
 [0.00406918]
 [0.05535042]
 [0.00415513]
 [0.00140417]
 [0.03280095]
 [0.00366767]]
loss :  [[0.06410002]
 [0.07678826]
 [0.00403757]
 [0.05517663]
 [0.00412844]
 [0.00139479]
 [0.03272003]
 [0.00364376]]
loss :  [[0.06390299]
 [0.07654922]
 [0.00400628]
 [0.0550036 ]
 [0.00410195]
 [0.00138549]
 [0.03263935]
 [0.00362005]]
loss :  [[0.06370675]
 [0.07631117]
 [0.00397529]
 [0.05483135]
 [0.00407568]
 [0.00137628]
 [0.03255891]
 [0.00359654]]
loss :  [[0.06351131]
 [0.0760741 ]
 [0.0039446 ]
 [0.05465987]
 [0.00404962]
 [0.00136715]
 [0.03247871]
 [0.00357322]]
loss :  [[0.06331664]
 [0.07583802]
 [0.00391421]
 [0.05448915]
 [0.00402377]
 [0.0013581 ]
 [0.03239876]
 [0.00355009]]
loss :  [[0.06312277]
 [0.07560291]
 [0.00388412]
 [0.05431919]
 [0.00399812]
 [0.00134913]
 [0.03231904]
 [0.00352716]]
loss :  [[0.06292